### ISSUE TITLE
Test (__tests__ dir and .github/workflows): propose to implement unittests and automation

### ISSUE THREAD

**Issue by KemingHe** [ad1992/fuzzify#3]
# Request Form

@ad1992 

## Issue

Current `yarn test` script gives placeholder echo statement in `package.json`

## Request

Implement automated unittesting through vitest and GitHub Actions to run per PR and merge (push) to main, aligning with project setup.

## Reason

I want to use this package and I want future versions to be bug-free when I `npm update`.

## Plan

1. Accept this issue.
2. Assign @KemingHe , tag as `test`.
3. I will open a PR with ONLY adding the testing automation by end of day 07/26.
4. Review, refactor or merge, and apply this issue as simple default issue template if you want.

Edit: grammar

**Comment by ad1992** [comment]
@KemingHe sure please go ahead and raise the PR

**Comment by KemingHe** [comment]
@ad1992 Delivered and revised in #8. Edit: update status.
