### ISSUE TITLE
Add semantic pr title GH action

### ISSUE THREAD

**Issue by ad1992** [ad1992/fuzzify#6]
Add ~https://github.com/marketplace/actions/pr-title-convention~ https://github.com/marketplace/actions/semantic-pull-request GH action to make sure every PR has a semantic title

**Comment by santoshyadavdev** [comment]
Let me take care of it 😃

**Comment by ad1992** [comment]
Sure Sir, most welcome ❤️

**Comment by ad1992** [comment]
closed via #7
